import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LikeProvider } from "@/context/LikeContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased py-4 px-10`}
      >
        <nav className="w-full flex gap-3 h-10 mb-10 border-b ">
          <Link href="/products">products</Link>
          <Link href="/favorites">favorites</Link>
        </nav>
        <LikeProvider>{children}</LikeProvider>
      </body>
    </html>
  );
}
